import Data.Numbers.Primes (isPrime, primes)
import Data.List (maximumBy)
import Data.Function (on)

-- Number of consecutive primes generated by x^2 + ax + b
nprimes :: Int -> Int -> Int
nprimes a b = length . takeWhile isPrime . map (\x -> x^2 + a*x + b) $ [0..]

solution = product . snd $ maximumBy (compare `on` fst) [(nprimes a b, [a, b]) | a <- as, b <- bs]
    where
        as = [-1000..1000]
        bs = takeWhile (< 1000) primes

main = print solution
